# File: tests/test_ignored_files.py

"""Tests for the IGNORED_FILES functionality."""

import shutil
from pathlib import Path

import pytest

from pyannotate.annotate_headers import IGNORED_FILES, process_file, walk_directory

# Directory for temporary test files
TEST_DIR = Path("tests/ignored_files_test")


@pytest.fixture(scope="module", autouse=True)
def setup_and_teardown():
    """Setup test environment and cleanup after tests."""
    if TEST_DIR.exists():
        shutil.rmtree(TEST_DIR)
    TEST_DIR.mkdir(parents=True)

    yield

    # Cleanup after tests
    shutil.rmtree(TEST_DIR)


def test_prettierrc_ignored():
    """Test that .prettierrc files are ignored."""
    prettierrc_file = TEST_DIR / ".prettierrc"
    original_content = """{
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5"
}"""
    prettierrc_file.write_text(original_content)

    # Process the file
    process_file(prettierrc_file, TEST_DIR)

    # Verify content is unchanged
    processed_content = prettierrc_file.read_text()
    assert (
        processed_content == original_content
    ), ".prettierrc file was modified but should be ignored"


def test_eslintrc_ignored():
    """Test that .eslintrc files are ignored."""
    eslintrc_file = TEST_DIR / ".eslintrc"
    original_content = """{
  "extends": ["eslint:recommended"],
  "env": {
    "node": true,
    "es2020": true
  },
  "rules": {
    "no-console": "warn"
  }
}"""
    eslintrc_file.write_text(original_content)

    # Process the file
    process_file(eslintrc_file, TEST_DIR)

    # Verify content is unchanged
    processed_content = eslintrc_file.read_text()
    assert (
        processed_content == original_content
    ), ".eslintrc file was modified but should be ignored"


def test_babelrc_ignored():
    """Test that .babelrc files are ignored."""
    babelrc_file = TEST_DIR / ".babelrc"
    original_content = """{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}"""
    babelrc_file.write_text(original_content)

    # Process the file
    process_file(babelrc_file, TEST_DIR)

    # Verify content is unchanged
    processed_content = babelrc_file.read_text()
    assert processed_content == original_content, ".babelrc file was modified but should be ignored"


def test_package_lock_json_ignored():
    """Test that package-lock.json files are ignored."""
    package_lock_file = TEST_DIR / "package-lock.json"
    original_content = """{
  "name": "test-project",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "test-project",
      "version": "1.0.0"
    }
  }
}"""
    package_lock_file.write_text(original_content)

    # Process the file
    process_file(package_lock_file, TEST_DIR)

    # Verify content is unchanged
    processed_content = package_lock_file.read_text()
    assert (
        processed_content == original_content
    ), "package-lock.json file was modified but should be ignored"


def test_yarn_lock_ignored():
    """Test that yarn.lock files are ignored."""
    yarn_lock_file = TEST_DIR / "yarn.lock"
    original_content = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0":
  version "7.12.11"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.11.tgz"
  integrity sha512-Zt1yodBx1UcyiePMSkWnU4hPqhwq7hGi2nFL1LeA3EUl+q2LQx16MISgJ0+z7dnmgvP9QtIleuETGOiOH1RcIw==
"""
    yarn_lock_file.write_text(original_content)

    # Process the file
    process_file(yarn_lock_file, TEST_DIR)

    # Verify content is unchanged
    processed_content = yarn_lock_file.read_text()
    assert (
        processed_content == original_content
    ), "yarn.lock file was modified but should be ignored"


def test_env_files_ignored():
    """Test that various .env files are ignored."""
    env_files = [".env.example", ".env.local", ".env.development", ".env.production"]

    for env_file_name in env_files:
        env_file = TEST_DIR / env_file_name
        original_content = """NODE_ENV=development
API_KEY=your_api_key_here
DATABASE_URL=postgres://localhost/myapp
"""
        env_file.write_text(original_content)

        # Process the file
        process_file(env_file, TEST_DIR)

        # Verify content is unchanged
        processed_content = env_file.read_text()
        assert (
            processed_content == original_content
        ), f"{env_file_name} file was modified but should be ignored"


def test_license_files_ignored():
    """Test that LICENSE files are ignored."""
    license_files = ["LICENSE", "COPYING", "NOTICE"]

    for license_file_name in license_files:
        license_file = TEST_DIR / license_file_name
        original_content = """MIT License

Copyright (c) 2025 Test Project

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files...
"""
        license_file.write_text(original_content)

        # Process the file
        process_file(license_file, TEST_DIR)

        # Verify content is unchanged
        processed_content = license_file.read_text()
        assert (
            processed_content == original_content
        ), f"{license_file_name} file was modified but should be ignored"


def test_ignored_files_constant():
    """Test that IGNORED_FILES constant contains expected files."""
    expected_files = {
        ".prettierrc",
        ".eslintrc",
        ".babelrc",
        "package-lock.json",
        "yarn.lock",
        ".env.example",
        ".env.local",
        ".env.development",
        ".env.production",
        "LICENSE",
        "COPYING",
        "NOTICE",
    }

    # Check that all expected files are in IGNORED_FILES
    for expected_file in expected_files:
        assert expected_file in IGNORED_FILES, f"{expected_file} should be in IGNORED_FILES"


def test_regular_files_still_processed():
    """Test that regular files are still processed normally."""
    js_file = TEST_DIR / "regular.js"
    original_content = """console.log("This should get a header");
"""
    js_file.write_text(original_content)

    # Process the file
    process_file(js_file, TEST_DIR)

    # Verify header was added
    processed_content = js_file.read_text()
    assert processed_content.startswith(
        "// File: regular.js"
    ), "Regular JS file should get a header"
    assert "console.log" in processed_content, "Original content should be preserved"


def test_multiple_ignored_files_in_directory():
    """Test processing a directory with multiple ignored files."""
    # Create multiple ignored files
    ignored_files_content = {
        ".prettierrc": '{"semi": false}',
        ".eslintrc": '{"extends": ["eslint:recommended"]}',
        "package-lock.json": '{"name": "test", "version": "1.0.0"}',
        ".env.example": "NODE_ENV=development",
    }

    # Create a regular file that should be processed
    regular_file = TEST_DIR / "app.py"
    regular_file.write_text("print('Hello, World!')")

    # Create ignored files
    for filename, content in ignored_files_content.items():
        file_path = TEST_DIR / filename
        file_path.write_text(content)

    # Process the entire directory
    walk_directory(TEST_DIR, TEST_DIR)

    # Verify ignored files are unchanged
    for filename, original_content in ignored_files_content.items():
        file_path = TEST_DIR / filename
        processed_content = file_path.read_text()
        assert (
            processed_content == original_content
        ), f"{filename} was modified but should be ignored"

    # Verify regular file got processed
    processed_regular = regular_file.read_text()
    assert processed_regular.startswith("# File: app.py"), "Regular Python file should get a header"
